// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: pkg/grpc/proto/agent.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType enum for different types of streaming events
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED   EventType = 0
	EventType_EVENT_TYPE_MESSAGE_START EventType = 1
	EventType_EVENT_TYPE_CONTENT       EventType = 2
	EventType_EVENT_TYPE_THINKING      EventType = 3
	EventType_EVENT_TYPE_TOOL_CALL     EventType = 4
	EventType_EVENT_TYPE_TOOL_RESULT   EventType = 5
	EventType_EVENT_TYPE_ERROR         EventType = 6
	EventType_EVENT_TYPE_COMPLETE      EventType = 7
	EventType_EVENT_TYPE_MESSAGE_STOP  EventType = 8
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_MESSAGE_START",
		2: "EVENT_TYPE_CONTENT",
		3: "EVENT_TYPE_THINKING",
		4: "EVENT_TYPE_TOOL_CALL",
		5: "EVENT_TYPE_TOOL_RESULT",
		6: "EVENT_TYPE_ERROR",
		7: "EVENT_TYPE_COMPLETE",
		8: "EVENT_TYPE_MESSAGE_STOP",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":   0,
		"EVENT_TYPE_MESSAGE_START": 1,
		"EVENT_TYPE_CONTENT":       2,
		"EVENT_TYPE_THINKING":      3,
		"EVENT_TYPE_TOOL_CALL":     4,
		"EVENT_TYPE_TOOL_RESULT":   5,
		"EVENT_TYPE_ERROR":         6,
		"EVENT_TYPE_COMPLETE":      7,
		"EVENT_TYPE_MESSAGE_STOP":  8,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_proto_agent_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pkg_grpc_proto_agent_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{0}
}

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN         HealthResponse_Status = 0
	HealthResponse_SERVING         HealthResponse_Status = 1
	HealthResponse_NOT_SERVING     HealthResponse_Status = 2
	HealthResponse_SERVICE_UNKNOWN HealthResponse_Status = 3
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_proto_agent_proto_enumTypes[1].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_grpc_proto_agent_proto_enumTypes[1]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{9, 0}
}

// RunRequest contains the input for agent execution
type RunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Input          string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Context        map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrgId          string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MaxIterations  int32                  `protobuf:"varint,4,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	ConversationId string                 `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *RunRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RunRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RunRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *RunRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// RunResponse contains the agent's response
type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RunStreamResponse for streaming responses
type RunStreamResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Chunk   string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	IsFinal bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Enhanced fields for richer streaming events
	EventType     EventType         `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=agent.EventType" json:"event_type,omitempty"`
	ToolCall      *ToolCall         `protobuf:"bytes,5,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	Thinking      string            `protobuf:"bytes,6,opt,name=thinking,proto3" json:"thinking,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64             `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStreamResponse) Reset() {
	*x = RunStreamResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStreamResponse) ProtoMessage() {}

func (x *RunStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStreamResponse.ProtoReflect.Descriptor instead.
func (*RunStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RunStreamResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *RunStreamResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *RunStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunStreamResponse) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *RunStreamResponse) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *RunStreamResponse) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *RunStreamResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunStreamResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ToolCall message for tool execution information
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "received", "executing", "completed", "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCall) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// MetadataRequest for getting agent metadata
type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{4}
}

// MetadataResponse contains agent metadata
type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataResponse) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *MetadataResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *MetadataResponse) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// CapabilitiesRequest for getting agent capabilities
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{6}
}

// CapabilitiesResponse contains agent capabilities
type CapabilitiesResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Tools                  []string               `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	SubAgents              []string               `protobuf:"bytes,2,rep,name=sub_agents,json=subAgents,proto3" json:"sub_agents,omitempty"`
	SupportsExecutionPlans bool                   `protobuf:"varint,3,opt,name=supports_execution_plans,json=supportsExecutionPlans,proto3" json:"supports_execution_plans,omitempty"`
	SupportsMemory         bool                   `protobuf:"varint,4,opt,name=supports_memory,json=supportsMemory,proto3" json:"supports_memory,omitempty"`
	SupportsStreaming      bool                   `protobuf:"varint,5,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilitiesResponse) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CapabilitiesResponse) GetSubAgents() []string {
	if x != nil {
		return x.SubAgents
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportsExecutionPlans() bool {
	if x != nil {
		return x.SupportsExecutionPlans
	}
	return false
}

func (x *CapabilitiesResponse) GetSupportsMemory() bool {
	if x != nil {
		return x.SupportsMemory
	}
	return false
}

func (x *CapabilitiesResponse) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

// HealthRequest for health checks
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{8}
}

// HealthResponse contains health status
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=agent.HealthResponse_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReadinessRequest for readiness checks
type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{10}
}

// ReadinessResponse contains readiness status
type ReadinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ReadinessResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadinessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PlanRequest for generating execution plans
type PlanRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Input          string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Context        map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrgId          string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *PlanRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *PlanRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PlanRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *PlanRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// PlanResponse contains the execution plan
type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	FormattedPlan string                 `protobuf:"bytes,2,opt,name=formatted_plan,json=formattedPlan,proto3" json:"formatted_plan,omitempty"`
	Steps         []*PlanStep            `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PlanResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanResponse) GetFormattedPlan() string {
	if x != nil {
		return x.FormattedPlan
	}
	return ""
}

func (x *PlanResponse) GetSteps() []*PlanStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *PlanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PlanStep represents a step in an execution plan
type PlanStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanStep) Reset() {
	*x = PlanStep{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanStep) ProtoMessage() {}

func (x *PlanStep) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanStep.ProtoReflect.Descriptor instead.
func (*PlanStep) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *PlanStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanStep) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *PlanStep) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ApprovalRequest for approving execution plans
type ApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Modifications string                 `protobuf:"bytes,3,opt,name=modifications,proto3" json:"modifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ApprovalRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ApprovalRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApprovalRequest) GetModifications() string {
	if x != nil {
		return x.Modifications
	}
	return ""
}

// ApprovalResponse contains the approval result
type ApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResponse) Reset() {
	*x = ApprovalResponse{}
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponse) ProtoMessage() {}

func (x *ApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponse.ProtoReflect.Descriptor instead.
func (*ApprovalResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ApprovalResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ApprovalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_grpc_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/grpc/proto/agent.proto\x12\x05agent\"\xff\x01\n" +
	"\n" +
	"RunRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x128\n" +
	"\acontext\x18\x02 \x03(\v2\x1e.agent.RunRequest.ContextEntryR\acontext\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12%\n" +
	"\x0emax_iterations\x18\x04 \x01(\x05R\rmaxIterations\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\vRunResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12<\n" +
	"\bmetadata\x18\x03 \x03(\v2 .agent.RunResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x02\n" +
	"\x11RunStreamResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12/\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x10.agent.EventTypeR\teventType\x12,\n" +
	"\ttool_call\x18\x05 \x01(\v2\x0f.agent.ToolCallR\btoolCall\x12\x1a\n" +
	"\bthinking\x18\x06 \x01(\tR\bthinking\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.agent.RunStreamResponse.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x11\n" +
	"\x0fMetadataRequest\"\x99\x02\n" +
	"\x10MetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12G\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2'.agent.MetadataResponse.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13CapabilitiesRequest\"\xdd\x01\n" +
	"\x14CapabilitiesResponse\x12\x14\n" +
	"\x05tools\x18\x01 \x03(\tR\x05tools\x12\x1d\n" +
	"\n" +
	"sub_agents\x18\x02 \x03(\tR\tsubAgents\x128\n" +
	"\x18supports_execution_plans\x18\x03 \x01(\bR\x16supportsExecutionPlans\x12'\n" +
	"\x0fsupports_memory\x18\x04 \x01(\bR\x0esupportsMemory\x12-\n" +
	"\x12supports_streaming\x18\x05 \x01(\bR\x11supportsStreaming\"\x0f\n" +
	"\rHealthRequest\"\xaa\x01\n" +
	"\x0eHealthResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.agent.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"\x12\n" +
	"\x10ReadinessRequest\"C\n" +
	"\x11ReadinessResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xda\x01\n" +
	"\vPlanRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x129\n" +
	"\acontext\x18\x02 \x03(\v2\x1f.agent.PlanRequest.ContextEntryR\acontext\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\fPlanResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12%\n" +
	"\x0eformatted_plan\x18\x02 \x01(\tR\rformattedPlan\x12%\n" +
	"\x05steps\x18\x03 \x03(\v2\x0f.agent.PlanStepR\x05steps\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xd9\x01\n" +
	"\bPlanStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12?\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\x1f.agent.PlanStep.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x0fApprovalRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12$\n" +
	"\rmodifications\x18\x03 \x01(\tR\rmodifications\"@\n" +
	"\x10ApprovalResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\xf8\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_MESSAGE_START\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_CONTENT\x10\x02\x12\x17\n" +
	"\x13EVENT_TYPE_THINKING\x10\x03\x12\x18\n" +
	"\x14EVENT_TYPE_TOOL_CALL\x10\x04\x12\x1a\n" +
	"\x16EVENT_TYPE_TOOL_RESULT\x10\x05\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x06\x12\x17\n" +
	"\x13EVENT_TYPE_COMPLETE\x10\a\x12\x1b\n" +
	"\x17EVENT_TYPE_MESSAGE_STOP\x10\b2\x82\x04\n" +
	"\fAgentService\x12,\n" +
	"\x03Run\x12\x11.agent.RunRequest\x1a\x12.agent.RunResponse\x12:\n" +
	"\tRunStream\x12\x11.agent.RunRequest\x1a\x18.agent.RunStreamResponse0\x01\x12>\n" +
	"\vGetMetadata\x12\x16.agent.MetadataRequest\x1a\x17.agent.MetadataResponse\x12J\n" +
	"\x0fGetCapabilities\x12\x1a.agent.CapabilitiesRequest\x1a\x1b.agent.CapabilitiesResponse\x125\n" +
	"\x06Health\x12\x14.agent.HealthRequest\x1a\x15.agent.HealthResponse\x12:\n" +
	"\x05Ready\x12\x17.agent.ReadinessRequest\x1a\x18.agent.ReadinessResponse\x12@\n" +
	"\x15GenerateExecutionPlan\x12\x12.agent.PlanRequest\x1a\x13.agent.PlanResponse\x12G\n" +
	"\x14ApproveExecutionPlan\x12\x16.agent.ApprovalRequest\x1a\x17.agent.ApprovalResponseB/Z-github.com/tagus/agent-sdk-go/pkg/grpc/pbb\x06proto3"

var (
	file_pkg_grpc_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_agent_proto_rawDescData []byte
)

func file_pkg_grpc_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_agent_proto_rawDesc), len(file_pkg_grpc_proto_agent_proto_rawDesc))) // #nosec G103
	})
	return file_pkg_grpc_proto_agent_proto_rawDescData
}

var file_pkg_grpc_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_grpc_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_grpc_proto_agent_proto_goTypes = []any{
	(EventType)(0),               // 0: agent.EventType
	(HealthResponse_Status)(0),   // 1: agent.HealthResponse.Status
	(*RunRequest)(nil),           // 2: agent.RunRequest
	(*RunResponse)(nil),          // 3: agent.RunResponse
	(*RunStreamResponse)(nil),    // 4: agent.RunStreamResponse
	(*ToolCall)(nil),             // 5: agent.ToolCall
	(*MetadataRequest)(nil),      // 6: agent.MetadataRequest
	(*MetadataResponse)(nil),     // 7: agent.MetadataResponse
	(*CapabilitiesRequest)(nil),  // 8: agent.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 9: agent.CapabilitiesResponse
	(*HealthRequest)(nil),        // 10: agent.HealthRequest
	(*HealthResponse)(nil),       // 11: agent.HealthResponse
	(*ReadinessRequest)(nil),     // 12: agent.ReadinessRequest
	(*ReadinessResponse)(nil),    // 13: agent.ReadinessResponse
	(*PlanRequest)(nil),          // 14: agent.PlanRequest
	(*PlanResponse)(nil),         // 15: agent.PlanResponse
	(*PlanStep)(nil),             // 16: agent.PlanStep
	(*ApprovalRequest)(nil),      // 17: agent.ApprovalRequest
	(*ApprovalResponse)(nil),     // 18: agent.ApprovalResponse
	nil,                          // 19: agent.RunRequest.ContextEntry
	nil,                          // 20: agent.RunResponse.MetadataEntry
	nil,                          // 21: agent.RunStreamResponse.MetadataEntry
	nil,                          // 22: agent.MetadataResponse.PropertiesEntry
	nil,                          // 23: agent.PlanRequest.ContextEntry
	nil,                          // 24: agent.PlanStep.ParametersEntry
}
var file_pkg_grpc_proto_agent_proto_depIdxs = []int32{
	19, // 0: agent.RunRequest.context:type_name -> agent.RunRequest.ContextEntry
	20, // 1: agent.RunResponse.metadata:type_name -> agent.RunResponse.MetadataEntry
	0,  // 2: agent.RunStreamResponse.event_type:type_name -> agent.EventType
	5,  // 3: agent.RunStreamResponse.tool_call:type_name -> agent.ToolCall
	21, // 4: agent.RunStreamResponse.metadata:type_name -> agent.RunStreamResponse.MetadataEntry
	22, // 5: agent.MetadataResponse.properties:type_name -> agent.MetadataResponse.PropertiesEntry
	1,  // 6: agent.HealthResponse.status:type_name -> agent.HealthResponse.Status
	23, // 7: agent.PlanRequest.context:type_name -> agent.PlanRequest.ContextEntry
	16, // 8: agent.PlanResponse.steps:type_name -> agent.PlanStep
	24, // 9: agent.PlanStep.parameters:type_name -> agent.PlanStep.ParametersEntry
	2,  // 10: agent.AgentService.Run:input_type -> agent.RunRequest
	2,  // 11: agent.AgentService.RunStream:input_type -> agent.RunRequest
	6,  // 12: agent.AgentService.GetMetadata:input_type -> agent.MetadataRequest
	8,  // 13: agent.AgentService.GetCapabilities:input_type -> agent.CapabilitiesRequest
	10, // 14: agent.AgentService.Health:input_type -> agent.HealthRequest
	12, // 15: agent.AgentService.Ready:input_type -> agent.ReadinessRequest
	14, // 16: agent.AgentService.GenerateExecutionPlan:input_type -> agent.PlanRequest
	17, // 17: agent.AgentService.ApproveExecutionPlan:input_type -> agent.ApprovalRequest
	3,  // 18: agent.AgentService.Run:output_type -> agent.RunResponse
	4,  // 19: agent.AgentService.RunStream:output_type -> agent.RunStreamResponse
	7,  // 20: agent.AgentService.GetMetadata:output_type -> agent.MetadataResponse
	9,  // 21: agent.AgentService.GetCapabilities:output_type -> agent.CapabilitiesResponse
	11, // 22: agent.AgentService.Health:output_type -> agent.HealthResponse
	13, // 23: agent.AgentService.Ready:output_type -> agent.ReadinessResponse
	15, // 24: agent.AgentService.GenerateExecutionPlan:output_type -> agent.PlanResponse
	18, // 25: agent.AgentService.ApproveExecutionPlan:output_type -> agent.ApprovalResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_agent_proto_init() }
func file_pkg_grpc_proto_agent_proto_init() {
	if File_pkg_grpc_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_agent_proto_rawDesc), len(file_pkg_grpc_proto_agent_proto_rawDesc)), // #nosec G103
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_agent_proto_depIdxs,
		EnumInfos:         file_pkg_grpc_proto_agent_proto_enumTypes,
		MessageInfos:      file_pkg_grpc_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_agent_proto = out.File
	file_pkg_grpc_proto_agent_proto_goTypes = nil
	file_pkg_grpc_proto_agent_proto_depIdxs = nil
}
